# Generated by Django 4.2.7 on 2025-09-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products_data',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
