# Generated by Django 4.2.7 on 2025-09-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_products_data_image_products_data_social_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_data',
            old_name='description',
            new_name='Product_description',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='name',
            new_name='Product_title',
        ),
    ]
