# Generated by Django 4.2.7 on 2025-09-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_description_products_data_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events_data',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='events_data',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='events_data',
            old_name='title',
            new_name='event_title',
        ),
        migrations.AddField(
            model_name='events_data',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='events_data',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
