# Generated by Django 4.2.7 on 2025-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_date_events_data_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_data',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
