# Generated by Django 4.2.7 on 2025-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_products_data_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_data',
            old_name='Product_description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='products_data',
            old_name='Product_title',
            new_name='product_title',
        ),
        migrations.RemoveField(
            model_name='products_data',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='products_data',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products_data',
            name='social_media',
            field=models.CharField(max_length=200),
        ),
    ]
