# Generated by Django 4.2.7 on 2025-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_product_description_products_data_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events_data',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='events_data',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='events_data',
            name='event_image',
        ),
        migrations.AddField(
            model_name='events_data',
            name='image',
            field=models.ImageField(default='events/default.jpg', upload_to='events/'),
        ),
        migrations.AddField(
            model_name='products_data',
            name='category',
            field=models.CharField(choices=[('AI-ML', 'AI-ML Products'), ('Cyber', 'Cyber Products'), ('General', 'General Products')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='events_data',
            name='event_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events_data',
            name='social_media',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='products_data',
            name='product_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products_data',
            name='social_media',
            field=models.URLField(),
        ),
    ]
