# Generated by Django 4.2.7 on 2025-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_events_data_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_data',
            name='category',
            field=models.CharField(choices=[('AI-ML', 'AI-ML Products'), ('Cyber', 'Cyber Products'), ('General', 'General Products')], max_length=10),
        ),
    ]
