# Generated by Django 4.2.7 on 2025-09-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_products_data_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_data',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
